-- ============================================================================
-- Renewal Dashboard — AUTH DB schema (PostgreSQL)
--
-- Port of backend/auth_schema.sql (originally MSSQL/T-SQL). Lives in a SEPARATE,
-- WRITABLE Postgres server we control. Business/renewal data stays read-only in
-- the company MSSQL (probus_autoboat_live) over the tunnel — NOT here.
--
-- Notes on the port:
--   * We keep the `dbo` schema so the app's existing `dbo.<table>` queries work
--     unchanged. (Postgres default is `public`; we deliberately use `dbo`.)
--   * BIT      -> boolean       BIGINT IDENTITY -> BIGINT GENERATED ... AS IDENTITY
--     NVARCHAR -> varchar/text  DATETIME2       -> timestamp (naive UTC, matches
--     SYSUTCDATETIME() semantics the app relies on)  SYSUTCDATETIME() -> now() at utc
--   * Idempotent: safe to run repeatedly (CREATE ... IF NOT EXISTS).
--
-- Run:
--   psql "postgresql://USER:PASSWORD@HOST:5432/renewal_auth?sslmode=require" -f 01_schema.sql
-- ============================================================================

CREATE SCHEMA IF NOT EXISTS dbo;

-- pgcrypto gives us crypt()/gen_salt('bf') so 02_seed.sql can bcrypt the super
-- admin password directly in SQL. On RDS/Cloud SQL this is an allowed extension.
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- 1. ROLES ------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dbo.roles (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_code   varchar(50)  NOT NULL UNIQUE,     -- SUPER_ADMIN | PRODUCT_HEAD | RENEWAL_HEAD | RENEWAL_TEAM
    role_name   varchar(100) NOT NULL,
    level       integer      NOT NULL,            -- 1=super admin, 2=product head, 3=renewal head, 4=renewal team (lower=stronger)
    description varchar(400),
    is_active   boolean      NOT NULL DEFAULT true,
    created_at  timestamp    NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),
    updated_at  timestamp    NOT NULL DEFAULT (now() AT TIME ZONE 'utc')
);

-- 2. USERS (auth accounts — ours, seeded FROM the company directory) --------
CREATE TABLE IF NOT EXISTS dbo.users (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username              varchar(100) NOT NULL UNIQUE,   -- company LoginId (e.g. P625131)
    email                 varchar(255),
    full_name             varchar(200),
    password_hash         varchar(255) NOT NULL,          -- bcrypt; compared in app
    role_id               BIGINT       NOT NULL REFERENCES dbo.roles(id),
    parent_id             BIGINT       REFERENCES dbo.users(id),   -- creator/owner; NULL for super
    company_user_id       BIGINT,                          -- vw_master_user.UserId (NO hard FK — cross-DB)
    is_active             boolean      NOT NULL DEFAULT true,
    must_change_password  boolean      NOT NULL DEFAULT true,
    failed_login_attempts integer      NOT NULL DEFAULT 0,
    locked_until          timestamp,
    last_login_at         timestamp,
    created_by            BIGINT       REFERENCES dbo.users(id),
    updated_by            BIGINT       REFERENCES dbo.users(id),
    created_at            timestamp    NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),
    updated_at            timestamp    NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),
    version               integer      NOT NULL DEFAULT 1,   -- optimistic locking
    CONSTRAINT chk_no_self_parent CHECK (parent_id IS NULL OR parent_id <> id)
);
CREATE INDEX IF NOT EXISTS idx_users_role   ON dbo.users(role_id);
CREATE INDEX IF NOT EXISTS idx_users_parent ON dbo.users(parent_id) WHERE parent_id IS NOT NULL;

-- 3. USER SCOPES (REGION / BRANCH / AM) -------------------------------------
-- A scoped user sees only rows matching ANY active scope. AM scope_value holds
-- the company AM_Id (== renewal am_id); REGION/BRANCH hold RegionName/BranchName.
CREATE TABLE IF NOT EXISTS dbo.user_scopes (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT       NOT NULL REFERENCES dbo.users(id),
    scope_type  varchar(10)  NOT NULL CHECK (scope_type IN ('REGION','BRANCH','AM')),
    scope_value varchar(150) NOT NULL,
    is_active   boolean      NOT NULL DEFAULT true,
    created_by  BIGINT       REFERENCES dbo.users(id),
    created_at  timestamp    NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),
    CONSTRAINT uq_user_scope UNIQUE (user_id, scope_type, scope_value)
);
CREATE INDEX IF NOT EXISTS idx_scope_user ON dbo.user_scopes(user_id);

-- 4. VIEWS (dashboard view catalog) -----------------------------------------
CREATE TABLE IF NOT EXISTS dbo.views (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    view_code   varchar(80)  NOT NULL UNIQUE,     -- DASHBOARD, POLICIES, USER_PROFILES, USER_MGMT, ...
    view_name   varchar(150) NOT NULL,
    description varchar(400),
    route       varchar(200) NOT NULL,            -- Angular path, e.g. /policies
    icon        varchar(80),
    category    varchar(80),
    config      text         NOT NULL DEFAULT '{}',   -- JSON string (kept as text; app parses it)
    sort_order  integer      NOT NULL DEFAULT 0,
    is_active   boolean      NOT NULL DEFAULT true,
    created_by  BIGINT       REFERENCES dbo.users(id),
    created_at  timestamp    NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),
    updated_at  timestamp    NOT NULL DEFAULT (now() AT TIME ZONE 'utc')
    -- (T-SQL had CHECK(ISJSON(config)=1); dropped for cross-version portability.
    --  If on PG16+, you may add: CHECK (config IS JSON))
);

-- 5. ROLE -> VIEW defaults --------------------------------------------------
CREATE TABLE IF NOT EXISTS dbo.role_view_access (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id    BIGINT  NOT NULL REFERENCES dbo.roles(id),
    view_id    BIGINT  NOT NULL REFERENCES dbo.views(id),
    can_view   boolean NOT NULL DEFAULT true,
    can_export boolean NOT NULL DEFAULT false,
    can_edit   boolean NOT NULL DEFAULT false,
    is_active  boolean NOT NULL DEFAULT true,
    created_by BIGINT  REFERENCES dbo.users(id),
    created_at timestamp NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),
    CONSTRAINT uq_role_view UNIQUE (role_id, view_id)
);

-- 6. USER -> VIEW override (grant/revoke per user) --------------------------
CREATE TABLE IF NOT EXISTS dbo.user_view_access (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT  NOT NULL REFERENCES dbo.users(id),
    view_id    BIGINT  NOT NULL REFERENCES dbo.views(id),
    is_granted boolean NOT NULL,                  -- true = extra grant, false = explicit revoke
    can_export boolean,                           -- NULL = inherit from role
    can_edit   boolean,
    created_by BIGINT  REFERENCES dbo.users(id),
    created_at timestamp NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),
    CONSTRAINT uq_user_view UNIQUE (user_id, view_id)
);

-- 7. REFRESH TOKENS (store only the SHA-256 hash) ---------------------------
CREATE TABLE IF NOT EXISTS dbo.refresh_tokens (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT    NOT NULL REFERENCES dbo.users(id),
    token_hash char(64)  NOT NULL,                -- sha256 hex; NEVER the raw token
    expires_at timestamp NOT NULL,
    revoked_at timestamp,
    user_agent varchar(400),
    ip         varchar(45),
    created_at timestamp NOT NULL DEFAULT (now() AT TIME ZONE 'utc')
);
CREATE INDEX IF NOT EXISTS idx_refresh_hash ON dbo.refresh_tokens(token_hash);

-- 8. AUDIT LOG --------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dbo.audit_log (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_id    BIGINT REFERENCES dbo.users(id),
    action      varchar(80) NOT NULL,             -- LOGIN, USER_CREATE, PASSWORD_RESET, SCOPE_ASSIGN, ...
    entity_type varchar(80),
    entity_id   BIGINT,
    details     text,                             -- JSON string (kept as text; app writes json.dumps)
    ip          varchar(45),
    created_at  timestamp NOT NULL DEFAULT (now() AT TIME ZONE 'utc')
);
CREATE INDEX IF NOT EXISTS idx_audit_created ON dbo.audit_log(created_at DESC);
